### ISSUE TITLE
Can't install latest versions from pip

### ISSUE THREAD

**Issue by damienalexandre** [objectrocket/elasticstat#16]
Hi there,

- The project does not seems to be up to date on pypi: https://pypi.python.org/pypi/elasticstat
- Running `pip install elasticstat` fetch 1.2.0
- Running `pip install 'elasticstat==1.3.1'` does not work
- Only solution I found was to run `pip install -Iv https://github.com/objectrocket/elasticstat/archive/1.3.1.tar.gz`

Thanks, :+1:

**Comment by paulrossmeier** [comment]
Hello - 

I will be looking into getting the latest version into pypi - please check back soon.
