### ISSUE TITLE
List object has no attribute 'strip'

### ISSUE THREAD

**Issue by khaliqgant** [objectrocket/elasticstat#17]
Hi, thanks for the utility! Running python version 2.7.10 I get this output when attempting to run

```
Traceback (most recent call last):
  File "/usr/local/bin/elasticstat", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/elasticstat/elasticstat.py", line 501, in main
    elasticstat.print_stats()
  File "/usr/local/lib/python2.7/site-packages/elasticstat/elasticstat.py", line 401, in print_stats
    self.active_master = self.es_client.cat.master(h="id").strip() # needed to remove trailing newline
AttributeError: 'list' object has no attribute 'strip'
```

Printing the content of `self.es_client.cat.master(h="id")` gives me `[{u'id': u'someRandomString'}]`

Simply removing the `.strip()` portion of the offending line generates output which I assume would be the expected output. Happy to help by submitting a PR if you can point me in the right direction.
 
Thanks!

**Comment by jtharpla** [comment]
Hello, what version of Elasticsearch were you connecting to when you encountered this?

**Comment by khaliqgant** [comment]
Thanks for the quick response, using 2.2.1

**Comment by kjbweb** [comment]
I too am running into this issue running Python v2.7.12 under Ubuntu 16.04.

**Comment by nrobert13** [comment]
Same here on centos7 , Python 2.7.5 , ES 2.3.5.
If I remove the .strip() from line 401, I get another error

```
Traceback (most recent call last):
  File "/bin/elasticstat", line 9, in <module>
    load_entry_point('elasticstat==1.2.0', 'console_scripts', 'elasticstat')()
  File "/usr/lib/python2.7/site-packages/elasticstat/elasticstat.py", line 501, in main
    elasticstat.print_stats()
  File "/usr/lib/python2.7/site-packages/elasticstat/elasticstat.py", line 418, in print_stats
    node_role = self.get_role(nodes_stats['nodes'][node_id]['attributes'])
KeyError: 'attributes'
```

**Comment by paulrossmeier** [comment]
This no longer seems to be an issue - please re-open if you run into this again

**Comment by pataquets** [comment]
@paulrossmeier : Still happening here:
```
elasticstat_1    | Traceback (most recent call last):
elasticstat_1    |   File "./elasticstat/elasticstat.py", line 568, in <module>
elasticstat_1    |     main()
elasticstat_1    |   File "./elasticstat/elasticstat.py", line 564, in main
elasticstat_1    |     elasticstat.print_stats()
elasticstat_1    |   File "./elasticstat/elasticstat.py", line 457, in print_stats
elasticstat_1    |     self.active_master = self.es_client.cat.master(h="id").strip() # needed to remove trailing newline
elasticstat_1    | AttributeError: 'list' object has no attribute 'strip'
```
Elasticsearch 2.4, single-node. Latest code.

**Comment by paulrossmeier** [comment]
Thank you for the update on the issue @pataquets

May I ask what version of python you are running?

I will look into this - thank you!

**Comment by pataquets** [comment]
I'm using a built from source image on Docker Hub:
```
$ docker run --rm -it --entrypoint python pataquets/elasticstat-src --version
Python 2.7.17
```
If you need to reproduce the whole thing, here it is the `docker-compose.yml` manifest I'm using for testing:
```
version: "2.4"
services:
  elasticsearch:
    image: elasticsearch:2.4

  elasticstat:
    image: pataquets/elasticstat-src
    command:
      - "--host"
      - "http://elasticsearch:9200"
    links:
      - elasticsearch
    restart: unless-stopped
```
Just do `docker-compose up` and eventually (that is, after ES is up) the error appears.
Happens also when pulling latest code and building the image locally (which can be avoided with #26 and using that image, too).
