### ISSUE TITLE
Make host a positional argument

### ISSUE THREAD

**Issue by DavidWittman** [objectrocket/elasticstat#2]
At the risk of rustling @melderan's jimmies, I'm going to suggest making the `host` value a positional argument instead of an optional argument.

The current interface for running elasticstat (with a delay of 5s) is:

``` bash
$ elasticstat -h 10.0.0.1:9200 5
```

I think this can be improved by instead making it:

``` bash
$ elasticstat --delay 5 10.0.0.1:9200
```

I'm suggesting this for a few reasons:

 - Prevent overloading of `-h`. This option is ubiquitously used for help, even in argparse.
 - The delay value is an optional positional argument which would make perfect sense to have as an option (e.g. `--delay`) instead.
 - The host "option" is going to be the most commonly set value in Elasticstat. I'd argue that this makes it the best candidate for the optional positional argument (defaulting to localhost).

**Comment by jtharpla** [comment]
My intention was to match the same command line options as mongostat :-) Sorry DW

**Comment by DavidWittman** [comment]
It's okay. Your intentions are wrong and I hate you. :)
