### ISSUE TITLE
Add to circleci v2

### ISSUE THREAD

**Issue by jbartels** [objectrocket/elasticstat#25]

**Comment by paulrossmeier** [comment]
I have added circleci in branch `updates_circleci_tox`

**Comment by jbartels** [comment]
@paulrossmeier you should link your PR here.  here are an example let me know if you need help.

https://help.github.com/en/github/writing-on-github/autolinked-references-and-urls or you can just do it in the UI here where it says "linked pull requests"

**Comment by paulrossmeier** [comment]
Thank you - 

I have just created the pull request here https://github.com/objectrocket/elasticstat/pull/27
