### ISSUE TITLE
Create Automated Build on Docker Hub

### ISSUE THREAD

**Issue by pataquets** [objectrocket/elasticstat#26]
Docker Hub allows you to create Automated Builds from source: https://docs.docker.com/docker-hub/builds/
It would add another packaging/distribution/installation method, whose buildings would be triggered automatically on each commit. It also allows to create different image tags automatically from git tags & branches.

By making the image build via an AB, you give the resulting image verifiability and auditability. Also, the build is fully automatic. You can have the latest image tag build from HEAD and individual image tags from git's release tags. Some people avoid non-verifiable (manually uploaded) images due to security & traceability reasons.

Since #23 is in, just a free Docker Hub account and a quick setup would do. Ping me if you need help.

**Comment by paulrossmeier** [comment]
Hello pataquets - 

Thanks for the update and suggestion.  I will take a look at this and then get back to you.

Have a great day

Paul Rossmeier
ObjectRocket Support

**Comment by pataquets** [comment]
@paulrossmeier Any news?

**Comment by pataquets** [comment]
@paulrossmeier I'm still interested in this issue. Pinging to prevent stalebot closing. If I can be of any help, let me know.

**Comment by pataquets** [comment]
@paulrossmeier The issue has been closed as stale. Any chance of disabling this instead of spamming it with keep-alives?
