### ISSUE TITLE
Elasticsearch 2.3 compatibility

### ISSUE THREAD

**Issue by damienalexandre** [objectrocket/elasticstat#8]
Hello and thanks for this tool,
I'm trying it on a ES 2.3 cluster and there is an error:

```
./elasticstat -h opa.arte.local               
cluster                           status   shards  pri relo init unassign   pending tasks   time    
elasticsearch                     yellow        4    4    0    0        4               0   11:14:35
Traceback (most recent call last):
  File "./elasticstat", line 9, in <module>
    load_entry_point('elasticstat==1.2.0', 'console_scripts', 'elasticstat')()
  File "/home/dalexandre/.local/lib/python2.7/site-packages/elasticstat/elasticstat.py", line 501, in main
    elasticstat.print_stats()
  File "/home/dalexandre/.local/lib/python2.7/site-packages/elasticstat/elasticstat.py", line 418, in print_stats
    node_role = self.get_role(nodes_stats['nodes'][node_id]['attributes'])
KeyError: 'attributes'
```

The script tries to guess a node role with the key `attributes` here: https://github.com/objectrocket/elasticstat/blob/6ec92a706e9ad93c43f335d68de3d103a7b82a49/elasticstat/elasticstat.py#L418 but the `/_nodes/stats` API does not have this kind of information on my cluster, running 2.3.3.

The cat API display this information but it's not easy to parse: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html

**Comment by philfreo** [comment]
+1
